name: kabelwerk_example_console
description: >-
  A very simple and crude console app showcasing the Kabelwerk SDK for Dart.

publish_to: none
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  args: ^2.4.2
  kabelwerk:
    path: ../../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
